# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache:
  - packages

env:
  - _R_CHECK_FORCE_SUGGESTS_=FALSE

addons:
  apt:
    packages:
      - tcl8.5-dev
      - tk8.5-dev

before_install:
    - export DISPLAY=:99.0

warnings_are_errors: false


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
  deploy:
    provider: script
    script: Rscript -e 'pkgdown::deploy_site_github()'
    skip_cleanup: true
